mvc_lists/config/routes.rb
Rails.application.routes.draw do
  get 'items/create'
  resources :lists do 
    resources :items 
  end 
  get 'lists/index'
  root 'lists#index'
end

mvc_lists/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mvc_lists/app/models/item.rb
class Item < ApplicationRecord
    belongs_to :list 
    validates :description, :presence => true
    
    STATUS = {
        :incomplete => false,
        :complete => true
    }

    def complete?
        self.status == STATUS[:complete]
    end 

    def incomplete?
        self.status == STATUS[:incomplete]
    end 

end

mvc_lists/app/models/list.rb
class List < ApplicationRecord
    has_many :items
    validates :name, :presence => true 
end

mvc_lists/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

mvc_lists/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save 
      redirect_to list_path(@list) 
    else 
      render "lists/show"
    end 
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)

    redirect_to list_path(@item.list)
  end 

  def show
    @item = Item.find(params[:id])
  end 

  def destroy
    @item = Item.find(params[:id])
    @item.destroy 

    redirect_to list_path(@item.list)
  end 

  private

  def item_params
    params.require(:item).permit(:description, :status)
  end 

end

mvc_lists/app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.new 
    @lists = List.all 
  end

  def show 
    @list = List.find(params[:id]) 
    @item = Item.new  
  end 

  def create 
    @list = List.new(list_params)
    if @list.save 
      redirect_to list_url(@list)
    else 
      @lists = List.all 
      render :index  
    end 
  end 

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    
    redirect_to '/lists'
  end 

  private 
    
    def list_params
      params.require(:list).permit(:name)
    end 
  
end

mvc_lists/app/helpers/application_helper.rb
module ApplicationHelper
end

mvc_lists/app/helpers/items_helper.rb
module ItemsHelper

    def li_class_for_item(item)
        "completed" if item.complete?
    end 
    
end

mvc_lists/app/helpers/lists_helper.rb
module ListsHelper
end

mvc_lists/app/views/items/_item_li.html.erb
<li class="<%= li_class_for_item(item) %>">
    <div class="view">
        <%= form_for([@list, item]) do |f| %>
            <%= f.hidden_field :status, value: !item.complete? %> 
            <%= f.submit item.complete? ? "Mark incomplete." : "Mark complete." %> 
        <% end %>

        <label><%= item.description %></label>

        <%= button_to "X", list_item_path(item.list, item), :method => "delete", :class => "destroy" %>
    </div>
</li>

mvc_lists/app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

mvc_lists/app/views/items/show.html.erb
<section class="todoapp">
    <header class="header">
        <h2><%= @item.description %></h2>
        <h3><%= @item.status %></h3>
    </header>
</section>

mvc_lists/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MvcLists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mvc_lists/app/views/lists/index.html.erb
<section class="todoapp">
    <header class="header">
	    <h1>Your Lists</h1>
        <%= form_for(@list) do |f| %>
            <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Enter a new list name.") %> 
            <%= f.submit :style => "display: none" %>
        <% end %> 

    <form>
    </header>
    <section class="main">
        <input class="toggle-all" type="checkbox">
        <label for="toggle-all">Mark all as complete.</label>
        <ul class="todo-list">
            <% @lists.each do |list| %>
            <li>
            <div class="view">
                <label><%= link_to list.name, list_path(list) %></label>
                <%= button_to "X", list_path(list), :method => "delete", :class => "destroy" %>
            </div>
            </li>
        <% end %> 
        </ul>
    </section>
    
    <footer class="footer">
	</footer>
</section>

mvc_lists/app/views/lists/show.html.erb
<section class="todoapp">
    <header class="header">
	    <h1><%= @list.name %></h1>
        <%= form_for([@list, @item]) do |f| %>
            <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item.") %> 
            <%= f.submit :style => "display: none" %>
        <% end %> 
    </header>
    
    <section class="main">
        <ul class="todo-list">
            <% @list.items.each do |item| %>
                <%= render :partial => "items/item_li", :locals => {:item => item} %>
            <% end %> 
        </ul>
    </section>
    <footer class="footer">
	</footer>
</section>